os:
- linux
- osx
language:
- cpp
dist: trusty
sudo: false
before_script: bash travis/before_install.sh
script: bash travis/script.sh
before_deploy:
- git config --local user.name kaizenman
- git config --local user.email makolyan2@ukr.net
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  api_key:
    secure: gyPkzMvmpumNtGv1qHerEEjaPebgdU/+CvnB3vX3yQZzJ5sZNiBSJvcPYATjFOeETlsXUlzBVnqh2uNCX/sl1fbJiI6JzukrNwgZsGtaHlIPguu1UlwFccO8c/O2BlowIM4B3fCrScLBi1ZQnRKQJLoM4TE4QUAaVDXLPIWCxJuMLPheJp8h+j/deS2mCTmeDp4LMLuKL8mXehyTYoN81/IOYpgY3nrvH5sGKj8Z83SfRO5UDZNx/zfq6gvrIpT/7a7rnICoPR4c10pnmK1oNTAoqtJNlwXBlv3DGk7qroGraAtvpthrcKextcKbgK2TovdN6HM4UJ1JqK4/HKCjCW/qsVIKvCK8jQite/Ie5eE6BPrTZ0OJn61XUZvso8B0RtvIyZWFcTNAoAnOWrq2ZlC+osCtLQxv1ae1hcvWU1ecL1LGo4vYBOO9nd8DHT+NINU8zCp7j+RfLps4mtUpeJO//Fk4VSxtutm7OQXV5zroh1q1fnYsNcKhwaU/YSAiKCtEkOW747zbLP5AfOfNnkuA0ZUydy7aIqawpEpZ5JSNZ2QxxzreK5xmnuH6lIa8Ph4n24NqD+MGM5/tWCmkDzowU1eZklaXwotfkzB52Iyxo/TCeG6mMMwDNmep5fEiwq9M1oUehInsF818Gm9K2YJvJDd7OIAUGHj/5foTThU=
  file:
  #- bin/run_linux
  - bin/run_darwin
  - bin/app-release.apk
  on:
    tags: false
  provider: releases
  skip_cleanup: true
branches:
  only:
  # release tags
  - /^v\d+\.\d+\.\d+.*$/
  - master