os:
- linux
- osx
language:
- cpp
dist: trusty
sudo: false
before_script: bash travis/before_install.sh
script: bash travis/script.sh
before_deploy:
- git config --local user.name kaizenman
- git config --local user.email makolyan2@ukr.net
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
before_install:
  - >-
    openssl aes-256-cbc 
    -K $encrypted_xxxxxxxxxxxx_key 
    -iv $encrypted_xxxxxxxxxxxx_iv 
    -in github_deploy_key.enc 
    -out github_deploy_key 
    -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key
deploy:
  file:
  #- bin/run_linux
  - bin/run_darwin
  - bin/app-release.apk
  on:
    tags: false
  provider: releases
  skip_cleanup: true
branches:
  only:
  # release tags
  - /^v\d+\.\d+\.\d+.*$/
  - master