os:
- linux
- osx
language:
- cpp
dist: trusty
sudo: false
before_script: bash travis/before_install.sh
script: bash travis/script.sh
before_deploy:
- git config --local user.name kaizenman
- git config --local user.email makolyan2@ukr.net
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  api_key:
    secure: "n97enAAtJTAz0TminixInxh9Z4u3RH4kx+iE9p1RPFlOPc8CSG0tphW7Wd2VwSWQb/1Fct+PWMIPdy9ZJO1EcnNda27iYQHYV8y0A3AcHRPqj/LkJkGPGBGTTu5D48mOx8LOzqnQEOCkqmb2LI7jr64WsrFeiRkzSYooI+zRrZSZztU50J5KAAJBp8X3wiXGV01X5QX8PKt3bCe7ax/JWBgIgtmv+1IDEv9XkHWNQHj88V4e6zNdoyIovMvRFccQMSAhYiZ6j7kMGHS3v1rJEx2Rb3HbdD9n0eAuSKPtkNNUpgSCmA/m09HdFq+8dmlGkK0Fr8RmgXgLft7CaF33P7bJ2TCc3sC0S2lvYp8tK23t5oXiWcq+DDHJiOHNI/6hmswAn/7pPJyw3J7hPAyahBhLZCWwQSNlNNd33smDcoNXoZCe6YGyeGPpVbCSeIvvywsTis2AHwMIL59izAw5hPqghc9wtt7emR8nv0Y+J/L656dhTQSuwHPbl7K3ek0Y29yh5QnAlZlaVk2GWGsQ7u+mXgTtck3qqBRHWoISfeax5BMk57edHD5XygiBZBBh2SkAq2i7eLNScQoTUJHGae1jCtzYEOKVbpx6NwrN5ooDRxH0ONFFSE6NpkjxpWt8W1OSeaYaBFjItuQJrDKVo9bka1eeCeTB2aIYqQ48p7w="
  file:
  - bin/run_darwin
  - bin/app-release.apk
  on:
    tags: false
  provider: releases
  skip_cleanup: true
branches:
  only:
  - "/^v\\d+\\.\\d+\\.\\d+.*$/"
  - master
