os:
- linux
- osx
language:
- cpp
dist: trusty
sudo: false
before_script: bash travis/before_install.sh
script: bash travis/script.sh
before_deploy:
- git config --local user.name kaizenman
- git config --local user.email makolyan2@ukr.net
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  api_key:
    secure: "VqEJBF9L4kTkXvr4PZgIebiYe6er0MMqilFSTNV+VTl7cEaShsQe5nXGp0fs6vB6NYKilRW+OXYLOW5OgeNjOhBL8ASfcNj1gCEe9+NvAqqaVCYHbgvr3OXiTBRswUo/4x/dQGfaIHXsTF/n1XggBLJQFmtiJDx/Mya/5MrVqTYiCvwix72GtKyLu/jSW3Ja5++zFPcR0eA/96MyWxhkgkeZh302ysCzo5IME4G0S5bFnMkMxcJKI4H39K74btQhkE2xrVnBwWROXkoAGxxgEshDqJuonE2ZaQA1EfCKJkzDE+xL2p4gIVPZpNw3iIMjmgGx6ONL/8QaDR7DrEmxYPebeXIAXHR+1ZceASFzmCkFFNLiOiffHnc53f0nP16ctfSJTsOufrH66PLzbkqVr5dK4TIAZnsQEPX8y6VMtQ5AWYgslfUEUu/xkVYFP/B9JdUHUZW57K2bdD0TIyIVRPdGZPs4qqfGru+/dkI2X+GlM3oticzAzR3zhRyxj8lwpXloIYbUxDX4hCy1CzvNOFcwEfIZUxU2cbYmNXW/GC9qbuuhD4iNzqkeCbt0pUOFvY5Phm8sggEeNJxKaxS6Azl34pu/BeddNZ1nK4b8dqgHoU4RznCGrBmRpEZ7OqPZOM11gfme4ih2ddHgPPlrIzZz5OHreRRm8dZMDvBthUI="
  file:
  - bin/run_darwin
  - bin/app-release.apk
  on:
    tags: false
  provider: releases
  skip_cleanup: true
branches:
  only:
  - "/^v\\d+\\.\\d+\\.\\d+.*$/"
  - master
